error: remove several enum variants from the top-level Error
We no longer use MiniscriptConstruction, MiniscriptParse, TypeCheck or
TapTreeDepthError.

When we do a similar replacement of the policy types' constructors with
strong error types, we will also be able to eliminate Parse, Threshold,
and Validation.